export const SUPABASE_URL = 'https://imhdhvvbepgnoqtpnglb.supabase.co';
export const SUPABASE_ANON_KEY = 'pk_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltaGRodnZiZXBnbm9xdHBuZ2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDc2NTUsImV4cCI6MjA3MDgyMzY1NX0.t_PkKQql03NTC91ExrOTGzOlRh2h_OGoikF8G1Xk4ow';


